from __future__ import annotations

import asyncio
import logging
from typing import Any

_LOGGER = logging.getLogger(__name__)
AUTO_DELAY_SECONDS = 90


def patch_auto_library_generation(WandrCoordinator) -> None:
    """Patch the coordinator with guarded first-run loop-library generation.

    Auto-generation is intentionally narrow:
    - loop/circle mode only
    - non-empty start/home address only
    - only when no route library exists yet for the current home/settings signature
    - only once per signature, so restarts do not hammer Overpass
    """

    original_async_load = WandrCoordinator.async_load
    original_update_option = WandrCoordinator.update_option
    original_generate_year = WandrCoordinator.generate_year
    original_shutdown = WandrCoordinator.shutdown

    async def async_load(self):
        await original_async_load(self)
        _schedule_auto_library_generation(self, reason="startup")

    async def update_option(self, key: str, value: Any, *, regenerate: bool = False):
        await original_update_option(self, key, value, regenerate=regenerate)
        if key in {"start_address", "loop_route", "route_count", "target_miles", "route_style"}:
            _schedule_auto_library_generation(self, reason=f"option:{key}")

    async def generate_year(self):
        await original_generate_year(self)
        if self.state.get("generation_status") in ("OK", "Generated with warnings"):
            signature = _auto_signature(self)
            if signature:
                self.state["route_library_autogenerated_signature"] = signature
                self.state["route_library_auto_attempted_signature"] = signature
                await self.save()

    async def shutdown(self):
        task = getattr(self, "_wandr_auto_library_task", None)
        if task and not task.done():
            task.cancel()
        await original_shutdown(self)

    WandrCoordinator.async_load = async_load
    WandrCoordinator.update_option = update_option
    WandrCoordinator.generate_year = generate_year
    WandrCoordinator.shutdown = shutdown


def _schedule_auto_library_generation(coord, *, reason: str) -> None:
    if not _should_auto_generate(coord):
        return
    existing = getattr(coord, "_wandr_auto_library_task", None)
    if existing and not existing.done():
        return
    coord._wandr_auto_library_task = coord.hass.loop.create_task(_run_auto_generate(coord, reason=reason))


async def _run_auto_generate(coord, *, reason: str) -> None:
    try:
        await asyncio.sleep(AUTO_DELAY_SECONDS)
        if not _should_auto_generate(coord):
            return
        signature = _auto_signature(coord)
        coord.state["route_library_auto_attempted_signature"] = signature
        coord.state["generation_status"] = "Auto-generating route library"
        coord.state["last_generation_summary"] = "Creating the first loop route library for this home address. This only runs automatically once per home/settings signature."
        await coord.save()
        _LOGGER.info("wandr auto-generating loop route library after %s", reason)
        await coord.generate_year()
    except asyncio.CancelledError:
        raise
    except Exception as err:
        _LOGGER.exception("wandr automatic route-library generation failed")
        signature = _auto_signature(coord)
        if signature:
            coord.state["route_library_auto_attempted_signature"] = signature
        coord.state["generation_status"] = "Auto-generation failed"
        coord.state["last_error"] = f"Automatic route-library generation failed: {err}"
        await coord.save()


def _should_auto_generate(coord) -> bool:
    signature = _auto_signature(coord)
    if not signature:
        return False
    if coord.state.get("route_library_autogenerated_signature") == signature:
        return False
    if coord.state.get("route_library_auto_attempted_signature") == signature:
        return False
    if coord.state.get("routes"):
        return False
    return True


def _auto_signature(coord) -> str | None:
    cfg = coord.entry.data

    def opt(key: str, default: Any = None) -> Any:
        value = coord.state.get(key)
        return value if value not in (None, "") else cfg.get(key, default)

    start_address = (opt("start_address", "") or "").strip()
    loop_route = bool(opt("loop_route", True))
    if not loop_route or not start_address:
        return None

    route_count = int(opt("route_count", 183) or 183)
    target_miles = float(opt("target_miles", 3.0) or 3.0)
    route_style = (opt("route_style", "Balanced") or "Balanced").strip()
    blacklist = (coord.state.get("blacklist") or "").strip()
    blocked_sections = coord.state.get("blocked_sections") or []
    blocked_key = repr(sorted((s.get("street", ""), s.get("from", ""), s.get("to", "")) for s in blocked_sections))

    return "|".join([
        start_address.lower(),
        f"count={route_count}",
        f"miles={target_miles:.2f}",
        f"style={route_style.lower()}",
        f"blacklist={blacklist.lower()}",
        f"blocked={blocked_key}",
    ])
