from __future__ import annotations

import asyncio
import json
import logging
from pathlib import Path
from typing import Any

from .coordinator import (
    WandrCoordinator,
    exportable_settings,
    render_directions_html,
    render_geojson,
    render_gpx,
    render_map_html,
)

_LOGGER = logging.getLogger(__name__)

AUTO_LIBRARY_DELAY_SECONDS = 90


class EnhancedWandrCoordinator(WandrCoordinator):
    """Coordinator with route-library and guarded first-run generation built in.

    This replaces the earlier monkey-patch approach. It keeps the existing route
    generation logic from WandrCoordinator, but owns:
    - compact route-library artifact writing
    - guarded one-time loop-library generation
    - library status/signature bookkeeping
    """

    def __init__(self, hass, entry) -> None:
        super().__init__(hass, entry)
        self._auto_library_task: asyncio.Task | None = None

        self.state.setdefault("library_status", "Not generated")
        self.state.setdefault("library_signature", "")
        self.state.setdefault("library_generated_at", "")
        self.state.setdefault("library_route_count", 0)
        self.state.setdefault("library_base_count", 0)
        self.state.setdefault("library_error", "")
        self.state.setdefault("route_library_autogenerated_signature", "")
        self.state.setdefault("route_library_auto_attempted_signature", "")

    async def async_load(self) -> None:
        await super().async_load()
        self._schedule_auto_library_generation(reason="startup")

    async def shutdown(self):
        if self._auto_library_task and not self._auto_library_task.done():
            self._auto_library_task.cancel()
        await super().shutdown()

    async def update_option(self, key: str, value: Any, *, regenerate: bool = False):
        await super().update_option(key, value, regenerate=regenerate)

        # If the user adds a home/start address or switches back to loop mode,
        # do the first-run route library generation, but only if it is actually
        # needed.
        if key in {
            "start_address",
            "loop_route",
            "route_count",
            "target_miles",
            "route_style",
            "blacklist",
            "blocked_sections",
        }:
            self._schedule_auto_library_generation(reason=f"option:{key}")

    async def generate_year(self):
        self.state["library_status"] = "Generating"
        self.state["library_error"] = ""
        self.state["generation_status"] = "Generating"
        self.state["last_generation_summary"] = "Generating routes. This can take a while for a full loop library."
        self.async_set_updated_data(self.state)

        await super().generate_year()

        if self.state.get("generation_status") in ("OK", "Generated with warnings"):
            signature = self._library_signature()
            self.state["library_signature"] = signature or ""
            self.state["route_library_autogenerated_signature"] = signature or self.state.get(
                "route_library_autogenerated_signature", ""
            )
            self.state["route_library_auto_attempted_signature"] = signature or self.state.get(
                "route_library_auto_attempted_signature", ""
            )
            self.state["library_status"] = "Ready"
            self.state["library_error"] = ""
            self.state["library_route_count"] = len(self.state.get("routes") or [])
            self.state["library_base_count"] = int(self.state.get("route_count") or self.entry.data.get("route_count") or 0)
            await self.save()
        elif self.state.get("generation_status") == "Error":
            self.state["library_status"] = "Error"
            self.state["library_error"] = self.state.get("last_error", "")
            await self.save()

    async def _write_artifacts(self):
        """Write current route artifacts and a compact local route library.

        This intentionally does NOT write GPX/GeoJSON/HTML for every route on
        every save. That was wasteful and made the integration feel heavier than
        it needed to be.

        Current route files stay available:
        - /local/wandr/current_route.json
        - /local/wandr/current_route.html
        - /local/wandr/current_directions.html
        - /local/wandr/current_route.gpx
        - /local/wandr/current_route.geojson

        Library files:
        - /local/wandr/routes/index.json
        - /local/wandr/routes/routes.min.json
        - /local/wandr/routes/routes.pretty.json
        """

        www = Path(self.hass.config.path("www/wandr"))
        route = self.current_route
        state_snapshot = dict(self.state)
        routes_snapshot = list(self.state.get("routes") or [])

        await self.hass.async_add_executor_job(
            _write_wandr_files_sync,
            www,
            state_snapshot,
            route,
            routes_snapshot,
            self._library_signature() or "",
        )

    def _schedule_auto_library_generation(self, *, reason: str) -> None:
        if not self._should_auto_generate_library():
            return

        if self._auto_library_task and not self._auto_library_task.done():
            return

        self._auto_library_task = self.hass.loop.create_task(
            self._auto_generate_library(reason=reason)
        )

    async def _auto_generate_library(self, *, reason: str) -> None:
        try:
            await asyncio.sleep(AUTO_LIBRARY_DELAY_SECONDS)

            if not self._should_auto_generate_library():
                return

            signature = self._library_signature()
            if not signature:
                return

            self.state["route_library_auto_attempted_signature"] = signature
            self.state["library_status"] = "Auto-generating"
            self.state["generation_status"] = "Auto-generating route library"
            self.state["last_generation_summary"] = (
                "Creating the first loop route library for this home address. "
                "This only runs automatically once for this home/settings signature."
            )
            await self.save()

            _LOGGER.info("wandr auto-generating route library after %s", reason)
            await self.generate_year()

        except asyncio.CancelledError:
            raise
        except Exception as err:
            _LOGGER.exception("wandr automatic route-library generation failed")
            signature = self._library_signature()
            if signature:
                self.state["route_library_auto_attempted_signature"] = signature
            self.state["library_status"] = "Auto-generation failed"
            self.state["generation_status"] = "Auto-generation failed"
            self.state["library_error"] = str(err)
            self.state["last_error"] = f"Automatic route-library generation failed: {err}"
            await self.save()

    def _should_auto_generate_library(self) -> bool:
        signature = self._library_signature()
        if not signature:
            return False

        if self.state.get("route_library_autogenerated_signature") == signature:
            return False

        if self.state.get("route_library_auto_attempted_signature") == signature:
            return False

        # Important: do not auto-regenerate if routes already exist. Manual
        # Generate Routes remains the intentional rebuild action.
        if self.state.get("routes"):
            return False

        return True

    def _library_signature(self) -> str | None:
        cfg = self.entry.data

        def opt(key: str, default: Any = None) -> Any:
            value = self.state.get(key)
            return value if value not in (None, "") else cfg.get(key, default)

        start_address = (opt("start_address", "") or "").strip()
        loop_route = bool(opt("loop_route", True))

        # Auto library generation is loop/circle only. A-to-B is user-requested.
        if not loop_route or not start_address:
            return None

        route_count = int(opt("route_count", 183) or 183)
        target_miles = float(opt("target_miles", 3.0) or 3.0)
        route_style = (opt("route_style", "Balanced") or "Balanced").strip()
        pace = float(opt("walking_minutes_per_mile", 20) or 20)
        blacklist = (self.state.get("blacklist") or "").strip()

        blocked_sections = self.state.get("blocked_sections") or []
        blocked_key = repr(
            sorted(
                (
                    (s.get("street", "") or "").strip().lower(),
                    (s.get("from", "") or "").strip().lower(),
                    (s.get("to", "") or "").strip().lower(),
                )
                for s in blocked_sections
            )
        )

        return "|".join(
            [
                f"home={start_address.lower()}",
                f"mode=loop",
                f"count={route_count}",
                f"miles={target_miles:.2f}",
                f"pace={pace:.2f}",
                f"style={route_style.lower()}",
                f"blacklist={blacklist.lower()}",
                f"blocked={blocked_key}",
            ]
        )


def _write_wandr_files_sync(
    www: Path,
    state: dict[str, Any],
    route: dict[str, Any],
    routes: list[dict[str, Any]],
    library_signature: str,
) -> None:
    www.mkdir(parents=True, exist_ok=True)

    (www / "current_route.html").write_text(render_map_html(route), "utf-8")
    (www / "current_route.json").write_text(json.dumps(route, indent=2), "utf-8")
    (www / "history.json").write_text(json.dumps(state.get("history", []), indent=2), "utf-8")
    (www / "current_directions.html").write_text(render_directions_html(route), "utf-8")
    (www / "current_route.gpx").write_text(render_gpx(route), "utf-8")
    (www / "current_route.geojson").write_text(render_geojson(route), "utf-8")
    (www / "settings_export.json").write_text(json.dumps(exportable_settings(state), indent=2), "utf-8")

    routes_dir = www / "routes"
    routes_dir.mkdir(parents=True, exist_ok=True)

    compact_routes = [_compact_route(route, idx) for idx, route in enumerate(routes, start=1)]

    index = {
        "version": 2,
        "library_signature": library_signature,
        "route_count": len(routes),
        "configured_base_route_count": state.get("route_count"),
        "loop_route": state.get("loop_route"),
        "target_miles": state.get("target_miles"),
        "route_style": state.get("route_style"),
        "start_address": state.get("start_address"),
        "end_address": state.get("end_address"),
        "current_index": state.get("current_index", 0),
        "current_route_name": route.get("name") if route else "",
        "routes_url": "/local/wandr/routes/routes.min.json",
        "pretty_routes_url": "/local/wandr/routes/routes.pretty.json",
        "note": (
            "Loop libraries use unique base loops plus mirrored clockwise/counterclockwise "
            "route instances. 183 base loops should produce 366 route instances."
        ),
        "routes": [
            {
                "index": r["index"],
                "name": r.get("name"),
                "mode": r.get("mode"),
                "direction": r.get("direction"),
                "distance_miles": r.get("distance_miles"),
                "duration_minutes": r.get("duration_minutes"),
                "elevation_gain_ft": r.get("elevation_gain_ft"),
                "quality_score": r.get("quality_score"),
            }
            for r in compact_routes
        ],
    }

    (routes_dir / "index.json").write_text(json.dumps(index, indent=2), "utf-8")
    (routes_dir / "routes.min.json").write_text(
        json.dumps(compact_routes, separators=(",", ":")),
        "utf-8",
    )
    (routes_dir / "routes.pretty.json").write_text(json.dumps(compact_routes, indent=2), "utf-8")


def _compact_route(route: dict[str, Any], index: int) -> dict[str, Any]:
    """Keep route data compact but complete enough for the card/export layer."""

    return {
        "index": index,
        "name": route.get("name"),
        "base_id": route.get("base_id"),
        "mode": route.get("mode"),
        "direction": route.get("direction"),
        "distance_miles": route.get("distance_miles"),
        "duration_minutes": route.get("duration_minutes"),
        "elevation_gain_ft": route.get("elevation_gain_ft"),
        "quality_score": route.get("quality_score"),
        "route_style": route.get("route_style"),
        "street_names": route.get("street_names") or [],
        "directions": route.get("directions") or [],
        "coords": route.get("coords") or [],
        "elevation_profile": route.get("elevation_profile") or [],
    }
