from __future__ import annotations

import asyncio
import json
import logging
from pathlib import Path
from typing import Any

from .coordinator import (
    Edge,
    M_PER_MILE,
    WandrCoordinator,
    exportable_settings,
    haversine,
    render_directions_html,
    render_geojson,
    render_gpx,
    render_map_html,
    section_label,
)
from .local_graph import async_get_local_walking_graph_data

_LOGGER = logging.getLogger(__name__)

AUTO_LIBRARY_DELAY_SECONDS = 90


class EnhancedWandrCoordinator(WandrCoordinator):
    """Coordinator with route-library, local graph cache, and guarded first-run generation.

    This replaces the earlier monkey-patch approach. It keeps the existing route
    generation logic from WandrCoordinator, but owns:
    - compact route-library artifact writing
    - guarded one-time loop-library generation
    - local walking graph cache usage
    - library status/signature bookkeeping
    """

    def __init__(self, hass, entry) -> None:
        super().__init__(hass, entry)
        self._auto_library_task: asyncio.Task | None = None

        self.state.setdefault("library_status", "Not generated")
        self.state.setdefault("library_signature", "")
        self.state.setdefault("library_generated_at", "")
        self.state.setdefault("library_route_count", 0)
        self.state.setdefault("library_base_count", 0)
        self.state.setdefault("library_error", "")
        self.state.setdefault("route_library_autogenerated_signature", "")
        self.state.setdefault("route_library_auto_attempted_signature", "")

        self.state.setdefault("local_graph_cache_status", "Not loaded")
        self.state.setdefault("local_graph_cache_path", "")
        self.state.setdefault("local_graph_radius_miles", None)
        self.state.setdefault("local_graph_element_count", 0)
        self.state.setdefault("local_graph_source", "")

    async def async_load(self) -> None:
        await super().async_load()
        self._schedule_auto_library_generation(reason="startup")

    async def shutdown(self):
        if self._auto_library_task and not self._auto_library_task.done():
            self._auto_library_task.cancel()
        await super().shutdown()

    async def update_option(self, key: str, value: Any, *, regenerate: bool = False):
        await super().update_option(key, value, regenerate=regenerate)

        if key in {
            "start_address",
            "loop_route",
            "route_count",
            "target_miles",
            "route_style",
            "blacklist",
            "blocked_sections",
        }:
            self._schedule_auto_library_generation(reason=f"option:{key}")

    async def generate_year(self):
        self.state["library_status"] = "Generating"
        self.state["library_error"] = ""
        self.state["generation_status"] = "Generating"
        self.state["last_generation_summary"] = "Generating routes. This can take a while for a full loop library."
        self.async_set_updated_data(self.state)

        await super().generate_year()

        if self.state.get("generation_status") in ("OK", "Generated with warnings"):
            signature = self._library_signature()
            self.state["library_signature"] = signature or ""
            self.state["route_library_autogenerated_signature"] = signature or self.state.get(
                "route_library_autogenerated_signature", ""
            )
            self.state["route_library_auto_attempted_signature"] = signature or self.state.get(
                "route_library_auto_attempted_signature", ""
            )
            self.state["library_status"] = "Ready"
            self.state["library_error"] = ""
            self.state["library_route_count"] = len(self.state.get("routes") or [])
            self.state["library_base_count"] = int(
                self.state.get("route_count") or self.entry.data.get("route_count") or 0
            )
            await self.save()

        elif self.state.get("generation_status") == "Error":
            self.state["library_status"] = "Error"
            self.state["library_error"] = self.state.get("last_error", "")
            await self.save()

    async def remove_selected_blocked_section(self):
        """Remove the selected avoid-list item.

        This is intentionally more forgiving than the base coordinator.

        The HA select entity can visually show the only blocked item even when
        selected_blocked_section is internally empty. In that case, pressing
        Remove used to do nothing. If there is exactly one blocked item, remove
        it even when the selected value is blank/stale.
        """

        sections = list(self.state.get("blocked_sections") or [])

        if not sections:
            self.state["selected_blocked_section"] = ""
            self.state["last_error"] = ""
            self.state["generation_status"] = "Avoid list already empty"
            self.state["last_generation_summary"] = "There are no blocked streets or sections to remove."
            await self.save()
            return

        selected = (self.state.get("selected_blocked_section") or "").strip()
        labels = [section_label(section) for section in sections]

        if selected and selected in labels:
            removed_label = selected
            remaining = [
                section
                for section in sections
                if section_label(section) != selected
            ]

        elif len(sections) == 1:
            removed_label = labels[0]
            remaining = []

        else:
            self.state["last_error"] = "Pick an avoid-list item before removing it."
            self.state["generation_status"] = "Avoid remove needs selection"
            self.state["last_generation_summary"] = (
                "More than one avoid-list item exists. Pick one from the Existing block dropdown first."
            )
            await self.save()
            return

        self.state["blocked_sections"] = remaining
        self.state["selected_blocked_section"] = section_label(remaining[0]) if remaining else ""

        # Keep the text fields in sync when the list is emptied.
        if not remaining:
            self.state["feedback_street"] = ""
            self.state["feedback_from_cross"] = ""
            self.state["feedback_to_cross"] = ""

        self.state["last_error"] = ""
        self.state["generation_status"] = "Avoid rule removed"
        self.state["last_generation_summary"] = (
            f"Removed avoid rule: {removed_label}. Press Generate Routes to rebuild routes around the updated avoid list."
        )
        await self.save()

    async def _download_graph(
        self,
        lat: float,
        lon: float,
        radius: int,
        blacklist: list[str],
        blocked_sections: list[dict[str, str]],
        start_lat: float,
        start_lon: float,
        end_lat: float,
        end_lon: float,
    ):
        """Load the walkable OSM graph from local cache, fetching it only if needed."""

        data, cache_meta = await async_get_local_walking_graph_data(
            self.hass,
            lat,
            lon,
            radius,
        )

        self.state["local_graph_cache_status"] = cache_meta.get("status", "unknown")
        self.state["local_graph_cache_path"] = cache_meta.get("path", "")
        self.state["local_graph_radius_miles"] = round(
            (cache_meta.get("radius_meters") or radius) / M_PER_MILE,
            2,
        )
        self.state["local_graph_element_count"] = cache_meta.get("element_count", 0)
        self.state["local_graph_source"] = cache_meta.get("source_url", "")

        normalized_blacklist = [
            normalize_street_match_text(item)
            for item in blacklist
            if normalize_street_match_text(item)
        ]

        nodes: dict[int, tuple[float, float]] = {}
        raw_ways: list[tuple[list[int], str, str]] = []

        for el in data.get("elements", []):
            if el.get("type") == "node":
                nodes[int(el["id"])] = (float(el["lat"]), float(el["lon"]))

            elif el.get("type") == "way":
                tags = el.get("tags", {})
                name = tags.get("name", "Unnamed path")
                highway = tags.get("highway", "")
                match_name = normalize_street_match_text(name)

                if any(
                    blocked and (blocked in match_name or match_name in blocked)
                    for blocked in normalized_blacklist
                ):
                    continue

                raw_ways.append(([int(n) for n in el.get("nodes", [])], name, highway))

        node_streets: dict[int, set[str]] = {}

        for way_nodes, name, _highway in raw_ways:
            match_name = normalize_street_match_text(name)

            if match_name:
                for node_id in way_nodes:
                    node_streets.setdefault(node_id, set()).add(match_name)

        sections = [normalize_section_for_matching(section) for section in blocked_sections]
        graph: dict[int, list[Edge]] = {node_id: [] for node_id in nodes}

        for way_nodes, name, highway in raw_ways:
            blocked_ranges = blocked_index_ranges_for_matching(
                way_nodes,
                name,
                node_streets,
                sections,
            )

            for idx, (a, b) in enumerate(zip(way_nodes[:-1], way_nodes[1:])):
                if a not in nodes or b not in nodes:
                    continue

                if edge_index_blocked(idx, blocked_ranges):
                    continue

                distance = haversine(nodes[a][0], nodes[a][1], nodes[b][0], nodes[b][1])
                graph[a].append(Edge(b, distance, name, highway))
                graph[b].append(Edge(a, distance, name, highway))

        if not nodes:
            raise RuntimeError("No walkable street data returned. Try again later or remove avoid-list items.")

        start_node = min(
            nodes,
            key=lambda node_id: haversine(
                start_lat,
                start_lon,
                nodes[node_id][0],
                nodes[node_id][1],
            ),
        )
        end_node = min(
            nodes,
            key=lambda node_id: haversine(
                end_lat,
                end_lon,
                nodes[node_id][0],
                nodes[node_id][1],
            ),
        )

        return graph, nodes, start_node, end_node

    async def _write_artifacts(self):
        """Write current route artifacts and a compact local route library."""

        www = Path(self.hass.config.path("www/wandr"))
        route = self.current_route
        state_snapshot = dict(self.state)
        routes_snapshot = list(self.state.get("routes") or [])

        await self.hass.async_add_executor_job(
            _write_wandr_files_sync,
            www,
            state_snapshot,
            route,
            routes_snapshot,
            self._library_signature() or "",
        )

    def _schedule_auto_library_generation(self, *, reason: str) -> None:
        if not self._should_auto_generate_library():
            return

        if self._auto_library_task and not self._auto_library_task.done():
            return

        self._auto_library_task = self.hass.loop.create_task(
            self._auto_generate_library(reason=reason)
        )

    async def _auto_generate_library(self, *, reason: str) -> None:
        try:
            await asyncio.sleep(AUTO_LIBRARY_DELAY_SECONDS)

            if not self._should_auto_generate_library():
                return

            signature = self._library_signature()
            if not signature:
                return

            self.state["route_library_auto_attempted_signature"] = signature
            self.state["library_status"] = "Auto-generating"
            self.state["generation_status"] = "Auto-generating route library"
            self.state["last_generation_summary"] = (
                "Creating the first loop route library for this home address. "
                "This only runs automatically once for this home/settings signature."
            )
            await self.save()

            _LOGGER.info("wandr auto-generating route library after %s", reason)
            await self.generate_year()

        except asyncio.CancelledError:
            raise

        except Exception as err:
            _LOGGER.exception("wandr automatic route-library generation failed")
            signature = self._library_signature()

            if signature:
                self.state["route_library_auto_attempted_signature"] = signature

            self.state["library_status"] = "Auto-generation failed"
            self.state["generation_status"] = "Auto-generation failed"
            self.state["library_error"] = str(err)
            self.state["last_error"] = f"Automatic route-library generation failed: {err}"
            await self.save()

    def _should_auto_generate_library(self) -> bool:
        signature = self._library_signature()

        if not signature:
            return False

        if self.state.get("route_library_autogenerated_signature") == signature:
            return False

        if self.state.get("route_library_auto_attempted_signature") == signature:
            return False

        if self.state.get("routes"):
            return False

        return True

    def _library_signature(self) -> str | None:
        cfg = self.entry.data

        def opt(key: str, default: Any = None) -> Any:
            value = self.state.get(key)
            return value if value not in (None, "") else cfg.get(key, default)

        start_address = (opt("start_address", "") or "").strip()
        loop_route = bool(opt("loop_route", True))

        if not loop_route or not start_address:
            return None

        route_count = int(opt("route_count", 183) or 183)
        target_miles = float(opt("target_miles", 3.0) or 3.0)
        route_style = (opt("route_style", "Balanced") or "Balanced").strip()
        pace = float(opt("walking_minutes_per_mile", 20) or 20)
        blacklist = normalize_street_match_text(self.state.get("blacklist") or "")

        blocked_sections = self.state.get("blocked_sections") or []
        blocked_key = repr(
            sorted(
                (
                    normalize_street_match_text(section.get("street", "") or ""),
                    normalize_street_match_text(section.get("from", "") or ""),
                    normalize_street_match_text(section.get("to", "") or ""),
                )
                for section in blocked_sections
            )
        )

        return "|".join(
            [
                f"home={start_address.lower()}",
                "mode=loop",
                f"count={route_count}",
                f"miles={target_miles:.2f}",
                f"pace={pace:.2f}",
                f"style={route_style.lower()}",
                f"blacklist={blacklist}",
                f"blocked={blocked_key}",
            ]
        )


def _write_wandr_files_sync(
    www: Path,
    state: dict[str, Any],
    route: dict[str, Any],
    routes: list[dict[str, Any]],
    library_signature: str,
) -> None:
    www.mkdir(parents=True, exist_ok=True)

    (www / "current_route.html").write_text(render_map_html(route), "utf-8")
    (www / "current_route.json").write_text(json.dumps(route, indent=2), "utf-8")
    (www / "history.json").write_text(json.dumps(state.get("history", []), indent=2), "utf-8")
    (www / "current_directions.html").write_text(render_directions_html(route), "utf-8")
    (www / "current_route.gpx").write_text(render_gpx(route), "utf-8")
    (www / "current_route.geojson").write_text(render_geojson(route), "utf-8")
    (www / "settings_export.json").write_text(json.dumps(exportable_settings(state), indent=2), "utf-8")

    routes_dir = www / "routes"
    routes_dir.mkdir(parents=True, exist_ok=True)

    compact_routes = [_compact_route(route_item, idx) for idx, route_item in enumerate(routes, start=1)]

    index = {
        "version": 2,
        "library_signature": library_signature,
        "route_count": len(routes),
        "configured_base_route_count": state.get("route_count"),
        "loop_route": state.get("loop_route"),
        "target_miles": state.get("target_miles"),
        "route_style": state.get("route_style"),
        "start_address": state.get("start_address"),
        "end_address": state.get("end_address"),
        "current_index": state.get("current_index", 0),
        "current_route_name": route.get("name") if route else "",
        "routes_url": "/local/wandr/routes/routes.min.json",
        "pretty_routes_url": "/local/wandr/routes/routes.pretty.json",
        "local_graph_cache_status": state.get("local_graph_cache_status"),
        "local_graph_cache_path": state.get("local_graph_cache_path"),
        "local_graph_radius_miles": state.get("local_graph_radius_miles"),
        "local_graph_element_count": state.get("local_graph_element_count"),
        "local_graph_source": state.get("local_graph_source"),
        "note": (
            "Loop libraries use unique base loops plus mirrored clockwise/counterclockwise "
            "route instances. 183 base loops should produce 366 route instances."
        ),
        "routes": [
            {
                "index": route_item["index"],
                "name": route_item.get("name"),
                "mode": route_item.get("mode"),
                "direction": route_item.get("direction"),
                "distance_miles": route_item.get("distance_miles"),
                "duration_minutes": route_item.get("duration_minutes"),
                "elevation_gain_ft": route_item.get("elevation_gain_ft"),
                "quality_score": route_item.get("quality_score"),
            }
            for route_item in compact_routes
        ],
    }

    (routes_dir / "index.json").write_text(json.dumps(index, indent=2), "utf-8")
    (routes_dir / "routes.min.json").write_text(
        json.dumps(compact_routes, separators=(",", ":")),
        "utf-8",
    )
    (routes_dir / "routes.pretty.json").write_text(json.dumps(compact_routes, indent=2), "utf-8")


def _compact_route(route: dict[str, Any], index: int) -> dict[str, Any]:
    return {
        "index": index,
        "name": route.get("name"),
        "base_id": route.get("base_id"),
        "mode": route.get("mode"),
        "direction": route.get("direction"),
        "distance_miles": route.get("distance_miles"),
        "duration_minutes": route.get("duration_minutes"),
        "elevation_gain_ft": route.get("elevation_gain_ft"),
        "quality_score": route.get("quality_score"),
        "route_style": route.get("route_style"),
        "street_names": route.get("street_names") or [],
        "directions": route.get("directions") or [],
        "coords": route.get("coords") or [],
        "elevation_profile": route.get("elevation_profile") or [],
    }


def normalize_street_match_text(value: str) -> str:
    text = (value or "").strip().lower()

    replacements = {
        ".": " ",
        ",": " ",
        "-": " ",
        "_": " ",
        " north ": " ",
        " south ": " ",
        " east ": " ",
        " west ": " ",
        " n ": " ",
        " s ": " ",
        " e ": " ",
        " w ": " ",
        " street ": " ",
        " st ": " ",
        " avenue ": " ",
        " ave ": " ",
        " boulevard ": " ",
        " blvd ": " ",
        " road ": " ",
        " rd ": " ",
        " drive ": " ",
        " dr ": " ",
        " lane ": " ",
        " ln ": " ",
        " way ": " ",
        " place ": " ",
        " pl ": " ",
        " court ": " ",
        " ct ": " ",
        " path ": " ",
        " trail ": " ",
    }

    text = f" {text} "

    for old, new in replacements.items():
        text = text.replace(old, new)

    edge_words = {
        "north",
        "south",
        "east",
        "west",
        "n",
        "s",
        "e",
        "w",
        "street",
        "st",
        "avenue",
        "ave",
        "boulevard",
        "blvd",
        "road",
        "rd",
        "drive",
        "dr",
        "lane",
        "ln",
        "way",
        "place",
        "pl",
        "court",
        "ct",
        "path",
        "trail",
    }

    parts = [part for part in text.split() if part not in edge_words]
    return " ".join(parts)


def normalize_section_for_matching(item: dict[str, str]) -> dict[str, str]:
    return {
        "street": normalize_street_match_text(item.get("street") or ""),
        "from": normalize_street_match_text(item.get("from") or ""),
        "to": normalize_street_match_text(item.get("to") or ""),
    }


def blocked_index_ranges_for_matching(
    way_nodes: list[int],
    name: str,
    node_streets: dict[int, set[str]],
    sections: list[dict[str, str]],
):
    ranges = []
    way_name = normalize_street_match_text(name)

    for section in sections:
        street = section.get("street") or ""

        if not street:
            continue

        if street not in way_name and way_name not in street:
            continue

        from_name = section.get("from") or ""
        to_name = section.get("to") or ""

        if not from_name and not to_name:
            ranges.append((0, max(0, len(way_nodes) - 2)))
            continue

        cross_indices = []

        for i, node_id in enumerate(way_nodes):
            names = node_streets.get(node_id, set())

            from_match = from_name and any(from_name in street_name or street_name in from_name for street_name in names)
            to_match = to_name and any(to_name in street_name or street_name in to_name for street_name in names)

            if from_match or to_match:
                cross_indices.append(i)

        if len(cross_indices) >= 2:
            a, b = min(cross_indices), max(cross_indices)
            ranges.append((a, max(a, b - 1)))

        else:
            ranges.append((0, max(0, len(way_nodes) - 2)))

    return ranges


def edge_index_blocked(idx: int, ranges: list[tuple[int, int]]) -> bool:
    return any(a <= idx <= b for a, b in ranges)
